### ISSUE TITLE
Cannot write unicode characters to lang files

### ISSUE THREAD

**Issue by vicen621** [yusshu/nmessage#18]
I am using this API for one of my plugins and when I try to write a unicode character in the langfile it replaces it with a sequence of random characters. The file is saved in UTF-8 and I am using sourcetype-bukkit-yml

Java: 17.0.8
Paper: 1.20.2-R0.1-SNAPSHOT

I remain at your disposal for any consultation.

**Comment by yusshu** [comment]
Should be fixed, version `7.2.2` *(should be available in our repository in a few minutes)*
